"""Generate 10 differentiated skills using deepseek-v4-pro (the judge_model).

Each skill is 100-400 Chinese characters of actionable instruction.
Output goes to skills/gen-<slug>.md with a metadata header.
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from arena.deepseek_client import DeepSeekClient  # noqa: E402

OUTPUT_DIR = PROJECT_ROOT / "skills"

# 10 skill specifications: (slug, category, one_line_style, category_hint)
SPECS: list[dict[str, str]] = [
    # 写作 (writing)
    {
        "slug": "persuasive-writer",
        "category": "writing",
        "style_hint": "以读者为中心的说服型写作,适合营销文案、提案、说服性邮件",
        "category_intro": "writing category — 说服型写作,目标是让读者采取行动或改变看法",
    },
    {
        "slug": "narrative-writer",
        "category": "writing",
        "style_hint": "故事化叙事写作,适合案例、品牌故事、个人反思",
        "category_intro": "writing category — 故事化叙事,用具体场景和人物带出观点",
    },
    # 编程 (coding)
    {
        "slug": "code-reviewer",
        "category": "coding",
        "style_hint": "代码审查视角,先列潜在 bug 与风险点,再给具体改进建议",
        "category_intro": "coding category — 代码审查,聚焦缺陷识别和改进建议",
    },
    {
        "slug": "sql-expert",
        "category": "coding",
        "style_hint": "SQL 专家,先分析数据特征与查询目的,再写出带注释的高效查询",
        "category_intro": "coding category — SQL 专家,分析先行,查询为后",
    },
    # 分析 (analysis)
    {
        "slug": "chain-of-thought",
        "category": "analysis",
        "style_hint": "显式 step-by-step 推理,适合复杂问题的分步分析",
        "category_intro": "analysis category — 链式思考,显式分步推理",
    },
    {
        "slug": "devils-advocate",
        "category": "analysis",
        "style_hint": "反方视角分析,主动寻找观点的弱点和盲区",
        "category_intro": "analysis category — 唱反调,主动攻击主流观点找漏洞",
    },
    # 元能力 (meta)
    {
        "slug": "self-critic",
        "category": "meta",
        "style_hint": "自检自纠,先给答案再挑刺再改,适合需要自我审查的回答",
        "category_intro": "meta category — 自我批评,先答后评再改",
    },
    {
        "slug": "step-back",
        "category": "meta",
        "style_hint": "先抽象再具体,先把握全局原则再落到执行细节",
        "category_intro": "meta category — 先退一步抽象,再回到具体",
    },
    # 格式约束 (format)
    {
        "slug": "json-only",
        "category": "format",
        "style_hint": "严格 JSON 输出,无任何额外文字,适合需要机器解析的产出",
        "category_intro": "format category — 严格 JSON 输出,无 markdown 包装",
    },
    {
        "slug": "markdown-table",
        "category": "format",
        "style_hint": "强制使用 Markdown 表格呈现对比型信息",
        "category_intro": "format category — 强制 Markdown 表格,适合多维对比",
    },
]


PROMPT_TEMPLATE = """你是一个 skill 编写专家。请为一个"技能竞技场"系统生成一份差异化 skill 文件。

## 任务
生成 1 份 skill,主题/类型: {style_hint}
类别: {category_intro}

## 严格要求
1. 用中文写,长度 100-400 字(指正文长度,不含元数据)
2. 包含可操作的指令(不要"写得简洁"这种空话),要让执行者知道具体怎么做
3. 必须明确:**适用场景**、**目标受众**、**风格定位**、**可操作步骤或规则**、**反例/不要做的事**
4. 不要再写"核心原则"这类同义反复的章节标题;要给出该 skill 独有的、具体到能照着做的指令
5. 输出格式:纯 markdown 正文(以 H1 标题开头),不要任何解释、不要任何前后缀

## 输出
只输出 markdown 文档本身,不要加 "以下是..." 之类的铺垫,也不要加代码块包裹。
"""


def call_v4_pro(client: DeepSeekClient, spec: dict[str, str]) -> str:
    """Call v4-pro via the judge() method (default model is judge_model = v4-pro)."""
    prompt = PROMPT_TEMPLATE.format(
        style_hint=spec["style_hint"],
        category_intro=spec["category_intro"],
    )
    messages = [
        {"role": "system", "content": "你是一个 skill 编写专家,只输出 markdown 文档。"},
        {"role": "user", "content": prompt},
    ]
    # judge() defaults to judge_model (= v4-pro) and temperature=0.2
    result = client.judge(messages, temperature=0.5)
    return result.content


def write_skill_file(spec: dict[str, str], body: str) -> Path:
    header = (
        f"# Source: generated by deepseek-v4-pro\n"
        f"# Generated: 2026-06-12\n"
        f"# Category: {spec['category']}\n"
        f"# Style: {spec['style_hint']}\n\n"
    )
    # Strip any leading/trailing whitespace and ensure body is the markdown
    body = body.strip()
    # If the model wrapped output in ```markdown ... ``` fences, unwrap
    if body.startswith("```"):
        lines = body.split("\n")
        # drop first fence line
        lines = lines[1:]
        # drop last fence line
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        body = "\n".join(lines).strip()
    content = header + body + "\n"
    out_path = OUTPUT_DIR / f"gen-{spec['slug']}.md"
    out_path.write_text(content, encoding="utf-8")
    return out_path


def chinese_char_count(text: str) -> int:
    """Count Chinese characters (CJK Unified Ideographs U+4E00–U+9FFF)
    plus ASCII word characters, since the spec asks 100-400 字 (characters)."""
    return sum(1 for ch in text if ("\u4e00" <= ch <= "\u9fff") or ch.isascii() and not ch.isspace())


def body_length(path: Path) -> int:
    """Count of the body (lines after the 4-line header)."""
    text = path.read_text(encoding="utf-8")
    lines = text.split("\n")
    body_lines: list[str] = []
    in_body = False
    for line in lines:
        if in_body:
            body_lines.append(line)
        elif line and not line.startswith("#"):
            in_body = True
            body_lines.append(line)
    body = "\n".join(body_lines).strip()
    # length = number of CJK chars + ASCII word chars (i.e. all non-whitespace, non-punct symbols? simpler: total non-whitespace chars)
    # Use total non-whitespace chars as the "字" proxy (closer to len(re.sub(r'\s','',body))).
    import re
    return len(re.sub(r"\s+", "", body))


def main() -> int:
    client = DeepSeekClient()
    print(f"[init] judge_model = {client.settings.judge_model}")

    rows: list[dict[str, object]] = []
    for spec in SPECS:
        print(f"\n[gen] {spec['slug']} ({spec['category']})")
        # Retry up to 3 times if length out of band
        body = ""
        path = None
        for attempt in range(3):
            body = call_v4_pro(client, spec)
            path = write_skill_file(spec, body)
            length = body_length(path)
            print(f"  attempt {attempt+1}: body length = {length} chars")
            if 100 <= length <= 400:
                break
            time.sleep(0.5)
        if path is None:
            print(f"  ERROR: failed to write {spec['slug']}")
            return 1
        final_length = body_length(path)
        rows.append(
            {
                "slug": spec["slug"],
                "category": spec["category"],
                "style": spec["style_hint"],
                "length": final_length,
                "path": path,
            }
        )

    print("\n=== Summary ===")
    for r in rows:
        flag = "OK" if 100 <= r["length"] <= 400 else "OUT"
        print(f"  [{flag}] {r['slug']:20s} {r['category']:8s} {r['length']:4d}  {r['style']}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
