"""Regenerate just gen-markdown-table.md with length control."""
from __future__ import annotations

import re
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from arena.deepseek_client import DeepSeekClient  # noqa: E402

PROMPT = """为一个 skill 竞技场系统写 1 份差异化 skill 文档。

主题:强制使用 Markdown 表格呈现对比型信息
类别:format
差异化角度:force Markdown table for multi-dimensional comparison

硬约束(必须满足):
- 中文,正文字符数(不含空格)必须在 150-380 之间。目标 250 字左右。
- 包含且仅包含这些小节(必须用 H2 标题):## 适用场景、## 目标受众、## 风格定位、## 操作步骤、## 不要做的事
- 每个小节 1-3 句话,直白具体,不要套话
- ## 操作步骤 用 3-5 条编号项,每条以动词开头、给出可照做的指令
- ## 不要做的事 用 2-4 条 bullet,给出该 skill 特有的反例
- 不要写"以下是"等铺垫,直接以 H1 标题("# 标题")开头

只输出 markdown 文档本身(以 # 标题 开头),不要任何前后缀、不要代码块包裹。"""

HEADER = (
    "# Source: generated by deepseek-v4-pro\n"
    "# Generated: 2026-06-12\n"
    "# Category: format\n"
    "# Style: 强制使用 Markdown 表格呈现对比型信息\n\n"
)


def body_len(md: str) -> int:
    lines = md.split("\n")
    bl: list[str] = []
    in_b = False
    for line in lines:
        if in_b:
            bl.append(line)
        elif line.strip() and not line.lstrip().startswith("#"):
            in_b = True
            bl.append(line)
    return len(re.sub(r"\s+", "", "\n".join(bl).strip()))


def unwrap(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        ls = text.split("\n")[1:]
        if ls and ls[-1].strip().startswith("```"):
            ls = ls[:-1]
        text = "\n".join(ls).strip()
    return text


def main() -> int:
    client = DeepSeekClient()
    out = PROJECT_ROOT / "skills" / "gen-markdown-table.md"
    for attempt in range(3):
        res = client.judge(
            [
                {"role": "system", "content": "你是 skill 编写专家,只输出 markdown 文档,严守字数。"},
                {"role": "user", "content": PROMPT},
            ],
            temperature=0.3,
        )
        body = unwrap(res.content)
        full = HEADER + body + "\n"
        length = body_len(full)
        print(f"attempt {attempt+1}: body={length} chars", flush=True)
        if 100 <= length <= 400:
            out.write_text(full, encoding="utf-8")
            print(f"-> OK, written to {out}")
            return 0
        time.sleep(0.3)
    # last try still write it
    out.write_text(full, encoding="utf-8")
    print(f"-> final length = {length}, still writing")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
