"""Generate v1 of gen-meta-prompt.md via deepseek-v4-pro (judge_model).

v4-pro is asked to do TWO things in one call:
  1. A meta-reflection preamble: explain HOW it will construct the meta-skill
     (this satisfies the "meta about meta" requirement from the task brief).
  2. The actual markdown body of the meta-skill.

The preamble is captured for the deliverable report; only the body is written
to skills/gen-meta-prompt.md as v1.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from arena.deepseek_client import DeepSeekClient  # noqa: E402

OUTPUT_PATH = PROJECT_ROOT / "skills" / "gen-meta-prompt.md"

# The two-stage prompt: reflection first, then body.
META_PROMPT = """你是一个"元 skill 工程师"。任务:为任意 agent 生成一份"工作哲学 + 方法论"元 prompt。

## 第一步:先写你的构造思路(2-4 句,中文,plain text)

在动手写 skill 之前,先用一段话回答:
1. 这个元 skill 与你之前可能写过的 self-critic / step-back / openai-meta-prompt 有什么本质不同?
2. 你打算把哪些可迁移的工作原则写进去?如何体现"先理解再动手""显式推理""输出可被验证"?

## 第二步:然后输出元 skill 的 markdown 主体(中文,正文 100-600 字)

元 skill 必须具备:
- **任务无关**:不绑定写作/编程/分析,任何 agent 都能用
- **agent 自适应**:能根据承接 agent 的强项调整自己的侧重点
- **持续打磨**:内置"使用后反思 → 提取模式 → 迭代 prompt"闭环
- **可被实际使用**:给一个具体场景(比如"接了一个模糊任务 X 时怎么用本 skill")

输出格式:
第一行写 "<META_REFLECTION>:" 紧跟你的构造思路文字,然后空一行,再输出 markdown 主体。
markdown 主体用 H1 标题(#)开头,结构化分节,但**不**要带任何解释性前后缀。
"""


def call_v4_pro(client: DeepSeekClient) -> str:
    messages = [
        {"role": "system", "content": "你是一个元 skill 工程师,中文输出,严格按两步格式。"},
        {"role": "user", "content": META_PROMPT},
    ]
    # temperature=0.5 to encourage the model to actually take the meta step
    return client.judge(messages, temperature=0.5).content


def split_reflection_and_body(raw: str) -> tuple[str, str]:
    """Parse "<META_REFLECTION>: ..." line(s) then the markdown body."""
    m = re.match(r"\s*<META_REFLECTION>:\s*(.*?)\n\s*\n(.*)", raw, re.DOTALL)
    if m:
        return m.group(1).strip(), m.group(2).strip()
    # fallback: no reflection tag found, treat whole thing as body
    return "", raw.strip()


def body_length(body: str) -> int:
    """Mirror gen_skills_v4pro.py body-length rule: non-whitespace char count."""
    return len(re.sub(r"\s+", "", body))


def write_v1(reflection: str, body: str) -> Path:
    header = (
        "# Source: generated by deepseek-v4-pro (with human-style meta-reflection)\n"
        "# Generated: 2026-06-12\n"
        "# Category: meta\n"
        "# Style: 工作哲学 + 自打磨方法论\n\n"
    )
    content = header + body + "\n"
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    return OUTPUT_PATH


def main() -> int:
    client = DeepSeekClient()
    print(f"[init] judge_model = {client.settings.judge_model}")

    print("[v1] calling v4-pro for meta-skill draft (with reflection preamble)...")
    raw = call_v4_pro(client)
    reflection, body = split_reflection_and_body(raw)

    print("\n--- META-REFLECTION (v4-pro's own construction plan) ---")
    print(reflection or "<none>")
    print(f"\n--- body length = {body_length(body)} chars ---")
    print(f"\n--- body preview (first 200 chars) ---\n{body[:200]}")

    path = write_v1(reflection, body)
    print(f"\n[ok] wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
