"""Regenerate all 10 skills with tight length control (100-400 chars body).

Strategy:
- Strong length instruction in prompt (target 200 chars, hard max 400)
- Validate body length after each call, retry up to 2x if out of band
- Sequential (one at a time) to avoid rate limits
"""
from __future__ import annotations

import re
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from arena.deepseek_client import DeepSeekClient  # noqa: E402

OUTPUT_DIR = PROJECT_ROOT / "skills"

SPECS: list[dict[str, str]] = [
    {"slug": "persuasive-writer", "category": "writing",
     "style": "以读者为中心的说服型写作,适合营销文案、提案、说服性邮件",
     "angle": "persuasion, action-oriented, reader's benefit first"},
    {"slug": "narrative-writer", "category": "writing",
     "style": "故事化叙事写作,适合案例、品牌故事、个人反思",
     "angle": "storytelling, scene-driven, character-focused"},
    {"slug": "code-reviewer", "category": "coding",
     "style": "代码审查视角,先列潜在 bug 与风险点,再给具体改进建议",
     "angle": "review, defect-hunt, suggestions, no rewrite"},
    {"slug": "sql-expert", "category": "coding",
     "style": "SQL 专家,先分析数据特征与查询目的,再写出带注释的高效查询",
     "angle": "analyze-first, then write efficient annotated SQL"},
    {"slug": "chain-of-thought", "category": "analysis",
     "style": "显式 step-by-step 推理,适合复杂问题的分步分析",
     "angle": "explicit numbered reasoning steps, no skipping"},
    {"slug": "devils-advocate", "category": "analysis",
     "style": "反方视角分析,主动寻找观点的弱点和盲区",
     "angle": "attack the dominant view, list weaknesses and blind spots"},
    {"slug": "self-critic", "category": "meta",
     "style": "自检自纠,先给答案再挑刺再改,适合需要自我审查的回答",
     "angle": "answer → critique → revise, self-review loop"},
    {"slug": "step-back", "category": "meta",
     "style": "先抽象再具体,先把握全局原则再落到执行细节",
     "angle": "abstract principle first, then concrete execution"},
    {"slug": "json-only", "category": "format",
     "style": "严格 JSON 输出,无任何额外文字,适合需要机器解析的产出",
     "angle": "strict JSON, no markdown, no preamble"},
    {"slug": "markdown-table", "category": "format",
     "style": "强制使用 Markdown 表格呈现对比型信息",
     "angle": "force Markdown table for multi-dimensional comparison"},
]


PROMPT = """为一个 skill 竞技场系统写 1 份差异化 skill 文档。

主题:{style}
类别:{category}
差异化角度:{angle}

硬约束(必须满足):
- 中文,正文字符数(不含空格)必须在 150-380 之间。目标 250 字左右。
- 包含且仅包含这些小节(必须用 H2 标题):## 适用场景、## 目标受众、## 风格定位、## 操作步骤、## 不要做的事
- 每个小节 1-3 句话,直白具体,不要套话
- ## 操作步骤 用 3-5 条编号项,每条以动词开头、给出可照做的指令
- ## 不要做的事 用 2-4 条 bullet,给出该 skill 特有的反例
- 不要写"以下是"等铺垫,直接以 H1 标题("# 标题")开头

只输出 markdown 文档本身(以 # 标题 开头),不要任何前后缀、不要代码块包裹。"""


HEADER_TEMPLATE = (
    "# Source: generated by deepseek-v4-pro\n"
    "# Generated: 2026-06-12\n"
    "# Category: {category}\n"
    "# Style: {style}\n\n"
)


def body_len(md_text: str) -> int:
    """Length of the markdown body, counting non-whitespace chars."""
    # strip header lines (start with # but not blank after)
    lines = md_text.split("\n")
    body_lines: list[str] = []
    in_body = False
    for line in lines:
        if in_body:
            body_lines.append(line)
        elif line.strip() and not line.lstrip().startswith("#"):
            in_body = True
            body_lines.append(line)
    body = "\n".join(body_lines).strip()
    return len(re.sub(r"\s+", "", body))


def unwrap_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        lines = text.split("\n")
        lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    return text


def call_one(client: DeepSeekClient, spec: dict[str, str]) -> str:
    messages = [
        {"role": "system", "content": "你是 skill 编写专家,只输出 markdown 文档,严守字数。"},
        {"role": "user", "content": PROMPT.format(
            style=spec["style"], category=spec["category"], angle=spec["angle"]
        )},
    ]
    res = client.judge(messages, temperature=0.4)
    return unwrap_fences(res.content)


def main() -> int:
    client = DeepSeekClient()
    print(f"[init] judge_model = {client.settings.judge_model}", flush=True)

    rows: list[dict[str, object]] = []
    for spec in SPECS:
        slug = spec["slug"]
        path = OUTPUT_DIR / f"gen-{slug}.md"
        print(f"\n[gen] {slug} ({spec['category']})", flush=True)
        body = ""
        length = 0
        for attempt in range(3):
            body = call_one(client, spec)
            full = (HEADER_TEMPLATE.format(category=spec["category"], style=spec["style"]) + body).strip()
            length = body_len(full)
            print(f"  attempt {attempt+1}: body={length} chars", flush=True)
            if 100 <= length <= 400:
                break
            time.sleep(0.3)
        # Final write
        full = HEADER_TEMPLATE.format(category=spec["category"], style=spec["style"]) + body.strip() + "\n"
        path.write_text(full, encoding="utf-8")
        final_len = body_len(full)
        rows.append({"slug": slug, "category": spec["category"],
                     "style": spec["style"], "length": final_len})
        status = "OK" if 100 <= final_len <= 400 else "OUT"
        print(f"  -> {status} {final_len} chars", flush=True)

    print("\n=== Summary ===")
    ok = 0
    for r in rows:
        flag = "OK " if 100 <= r["length"] <= 400 else "OUT"
        if flag == "OK ":
            ok += 1
        print(f"  [{flag}] {r['slug']:22s} {r['category']:8s} {r['length']:4d}  {r['style']}")
    print(f"\n{ok}/{len(rows)} in 100-400 range")
    return 0 if ok == len(rows) else 1


if __name__ == "__main__":
    raise SystemExit(main())
