"""Final verification for track5 deliverable.

Reports BOTH the project's gen_skills_v4pro.py measurement (Method A, skip
lines starting with #) AND the post-4-line-header measurement (Method B,
which is what the verifier used to count 623 on the previous attempt and
reject it as 24 over the 600 cap).

Prints PASS/FAIL for every spec requirement. Verdict only passes if BOTH
methods land in [100, 600] AND all content checks pass.
"""
import re
from pathlib import Path

PATH = Path(r"E:\Projects\skill竞技场\skills\gen-meta-prompt.md")
text = PATH.read_text(encoding="utf-8")
lines = text.split("\n")

# Method A: mirrors gen_skills_v4pro.body_length() — skip lines starting with '#'
body_a_lines = []
in_body = False
for line in lines:
    if in_body:
        body_a_lines.append(line)
    elif line and not line.startswith("#"):
        in_body = True
        body_a_lines.append(line)
body_a = "\n".join(body_a_lines).strip()
n_a = len(re.sub(r"\s+", "", body_a))

# Method B: everything after the 4-line metadata header (this is what the
# track5 verifier measured and rejected at 623)
body_b = "\n".join(lines[4:]).strip()
n_b = len(re.sub(r"\s+", "", body_b))

print("--- HEADER (first 4 lines) ---")
for line in lines[:4]:
    print(f"  {line}")
print()

print("--- LENGTH (both measurement methods) ---")
print(f"  Method A (skip # lines, project convention): {n_a} chars")
print(f"  Method B (post 4-line header, verifier):    {n_b} chars")
print()

# Content checks (against the whole file so H2 section headers count)
def in_text(s: str) -> bool:
    return s in text


checks = {
    "header Source line":       lines[0].startswith("# Source: generated by deepseek-v4-pro"),
    "header Generated":         lines[1].startswith("# Generated: 2026-06-12"),
    "header Category: meta":    lines[2].startswith("# Category: meta"),
    "header Style line":        lines[3].startswith("# Style:"),
    f"Method A length in [100,600] (actual={n_a})": 100 <= n_a <= 600,
    f"Method B length in [100,600] (actual={n_b})": 100 <= n_b <= 600,
    "has ## 三条贯穿原则":        in_text("## 三条贯穿原则"),
    "has ## agent 自适应":       in_text("## agent 自适应"),
    "has ## 行动节奏":           in_text("## 行动节奏"),
    "has ## 自打磨闭环":         in_text("## 自打磨闭环"),
    "has ## 场景示例":           in_text("## 场景示例"),
    "mentions 先理解再动手":     in_text("先理解再动手"),
    "mentions 显式推理":         in_text("显式推理"),
    "mentions 可被验证":         in_text("可被验证"),
    "mentions 复盘/提模式/写回": all(in_text(k) for k in ["复盘", "提模式", "写回"]),
    "concrete example (竞品 + 理解摘要)": in_text("竞品") and in_text("理解摘要"),
    "agent 自适应 mentions 3 agent types": all(
        in_text(t) for t in ["分析型 agent", "写作型 agent", "代码型 agent"]
    ),
}

print("--- CONTENT CHECKS ---")
all_pass = True
for k, v in checks.items():
    flag = "PASS" if v else "FAIL"
    if not v:
        all_pass = False
    print(f"  [{flag}] {k}")

print()
print("OVERALL:", "ALL PASS" if all_pass else "SOME FAIL")
